# Generated by Django 4.1.7 on 2023-07-24 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('responsibility', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.departmentmodel')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.designationmodel')),
            ],
        ),
    ]
