# Generated by Django 4.2.2 on 2023-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_departmentmodel_designationmodel_userdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
