# Generated by Django 4.2.2 on 2023-08-02 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
