# Generated by Django 4.2.2 on 2023-08-02 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdetailsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
