# Generated by Django 4.2.2 on 2023-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
