# Generated by Django 4.2.2 on 2023-08-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdetailsmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
