# Generated by Django 4.2.2 on 2023-08-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_bankdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={},
        ),
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.departmentmodel'),
        ),
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.designationmodel'),
        ),
    ]
