# Generated by Django 4.2.2 on 2023-08-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_bankdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
    ]
