# Generated by Django 4.2.2 on 2023-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_taxpercentage_minimum_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='month',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
