# Generated by Django 4.2.2 on 2023-08-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_monthlypayment_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='user_details',
        ),
    ]
