# Generated by Django 4.2.2 on 2023-08-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_monthlypayment_gross_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
