# Generated by Django 4.2.2 on 2023-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_monthlypayment_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
