# Generated by Django 4.2.2 on 2023-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_monthlypayment_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
